<?php

namespace corehat\core;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-11 at 03:27:42.
 */
class PluginTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Plugin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Plugin;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers corehat\core\Plugin::LoadPlugin
     * @todo   Implement testLoadPlugin().
     */
    public function testLoadPlugin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\core\Plugin::InstallPlugin
     * @todo   Implement testInstallPlugin().
     */
    public function testInstallPlugin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\core\Plugin::UnstallPlugin
     * @todo   Implement testUnstallPlugin().
     */
    public function testUnstallPlugin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
