<?php

namespace corehat\core;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-11 at 03:27:42.
 */
class SystemTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var System
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new System;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers corehat\core\System::start
     * @todo   Implement testStart().
     */
    public function testStart() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\core\System::plugin_exists
     * @todo   Implement testPlugin_exists().
     */
    public function testPlugin_exists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
