<?php

namespace corehat\utils;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-11 at 03:26:11.
 */
class debugTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var debug
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new debug;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers corehat\utils\debug::debugRun
     * @todo   Implement testDebugRun().
     */
    public function testDebugRun() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\utils\debug::echoLine
     * @todo   Implement testEchoLine().
     */
    public function testEchoLine() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\utils\debug::debugWords
     * @todo   Implement testDebugWords().
     */
    public function testDebugWords() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\utils\debug::debugarray
     * @todo   Implement testDebugarray().
     */
    public function testDebugarray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\utils\debug::echoBr
     * @todo   Implement testEchoBr().
     */
    public function testEchoBr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\utils\debug::echoCount
     * @todo   Implement testEchoCount().
     */
    public function testEchoCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\utils\debug::echoEspecial
     * @todo   Implement testEchoEspecial().
     */
    public function testEchoEspecial() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\utils\debug::print_rr
     * @todo   Implement testPrint_rr().
     */
    public function testPrint_rr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\utils\debug::print_rrd
     * @todo   Implement testPrint_rrd().
     */
    public function testPrint_rrd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\utils\debug::print_rd
     * @todo   Implement testPrint_rd().
     */
    public function testPrint_rd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\utils\debug::print_rh
     * @todo   Implement testPrint_rh().
     */
    public function testPrint_rh() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\utils\debug::print_rrh
     * @todo   Implement testPrint_rrh().
     */
    public function testPrint_rrh() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\utils\debug::print_rhd
     * @todo   Implement testPrint_rhd().
     */
    public function testPrint_rhd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\utils\debug::print_in_table
     * @todo   Implement testPrint_in_table().
     */
    public function testPrint_in_table() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers corehat\utils\debug::debugWebmaster
     * @todo   Implement testDebugWebmaster().
     */
    public function testDebugWebmaster() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
